logging:
  level: info
  format: '%(timestamp)s [%(level)s] %(message)s'
  
  file:
    enabled: true
    path: logs/app.log
    max_size: 10MB
    backup_count: 5
    
  console:
    enabled: true
    color: true
    
  categories:
    api:
      level: info
      handlers: [console, file]
    
    scraper:
      level: debug
      handlers: [console, file]
      
    bot:
      level: info
      handlers: [console, file]
      
    payment:
      level: info
      handlers: [console, file]
      
    security:
      level: warn
      handlers: [console, file]